opendatahub-io/data-science-pipelines

backend/src/v2/component/importer_launcher.go, backend/src/v2/component/launcher_v2.go, backend/src/v2/config/env.go, backend/src/v2/driver/driver.go, backend/src/v2/metadata/client.go, backend/src/v2/metadata/client_fake.go, backend/src/v2/metadata/client_test.go, backend/src/v2/objectstore/object_store.go
Resolve [RHOAIENG-1707](https://issues.redhat.com/browse/RHOAIENG-1707) from dsp side
Adds the ability to specify pipeline root based on prefix within a namespace. This pr allows users to: 
1. provide different credentials for different paths 
2. configure non aws s3 compatible artifact stores 
3. allow tls configuration for artifact store connection
4. adds a new custom property to mlmd `bucket_session_info`, this is added by the root driver container, so we read the kfp-launcher configmap once per pipeline
I would have preferred to organize this very differently but as this is a carried patch I've tried to minimize code deletions to make it easy to merge in upstream changes and minimize conflicts.
**Testing changes** 
Deploy a kfp-launcher configmap that …
=> UPSTREAM: <carry>: add ns scoped s3 support.

.github/workflows/build-images.yaml, .github/workflows/build-master.yml, .github/workflows/build-prs.yml, .github/workflows/tag-release-quay.yml
the following images are not used in dsp v2 argo: 
* viewer controller
* cache server
* metadata writer
* artifact step copy image
=> UPSTREAM: <carry>: remove unused images for v2.

backend/src/apiserver/model/run.go
See for model name for experiment id : 
https://github.com/kubeflow/pipelines/blob/d4c43f77bc38080506794377647ce5b1d9f18bdf/backend/src/apiserver/storage/run_store.go#L33
=> UPSTREAM: <carry>: correct typo in experiment model

backend/src/apiserver/model/job.go, backend/src/apiserver/model/run.go
namely pipeline name, id, and pipeline version id filters for jobs & runs
Testing instructions: 
1. Deploy DSP with the api server that has these changes
2. Create a run, and a recurring run (job/scheduled run/etc.)
3. Either via curl or postman do a GET on the run and job that were created and filter on the added fields (pipeline_id, pipeline_name, pipeline_version_id)
Example: 
In the examples above {{dsp-route}} is just the api route you can fetch from ocp console, and don't forget to use the bearer token (gotten via `oc whoami --show-token`)
=> UPSTREAM: <carry>: feat: expose more filters for runs/jobs

backend/src/v2/compiler/argocompiler/container.go
Launcher writes input artifacts to root paths /gcs, /minio, and /s3. These paths are not accessible by non-root users by default, which is problematic in locked-down Kubernetes installations and/or OpenShift. /gcs is currently a contract for KFP v2 python component wrappers, so the path cannot be changed.
Mount an EmptyDir scratch volume to these paths to work around this.
Additionally, /.local and /.cache are written to by pip, so add EmptyDir mounts for those too.
Fixes: https://issues.redhat.com/browse/RHOAIENG-1889
Ref: https://github.com/kubeflow/pipelines/issues/5673
Ref: https://github.com/kubeflow/pipelines/issues/7345
Using the kfp 2.6.0+ SDK, compile the test pipeline here https://github.com/gregsheremeta/gists/blob/main/test-iris-pipeline.py  (or use the pre-compiled pipeline …
=> UPSTREAM: <carry>: feat: mount EmptyDir volumes for launcher write locations

backend/src/v2/cmd/driver/execution_paths.go, backend/src/v2/cmd/driver/main.go, backend/src/v2/cmd/driver/main_test.go
Resolves https://issues.redhat.com/browse/RHOAIENG-1629
Cherry picked from https://github.com/kubeflow/pipelines/pull/10459
Deploy and run https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/samples/v2/dspa-simple/dspa_simple.yaml with the `quay.io/opendatahub/ds-pipelines-driver:pr-20` driver image.
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
name: sample
spec:
dspVersion: v2
objectStorage:
minio:
deploy: true
image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
mlpipelineUI:
image: quay.io/opendatahub/ds-pipelines-frontend:latest
apiServer:
argoDriverImage: quay.io/opendatahub/ds-pipelines-driver:pr-20
```
=> fix(backend): fixes "cannot save parameter" error message. Fixes #9678 (#10459)

backend/src/v2/compiler/argocompiler/container.go
Resolves [RHOAIENG-1810](https://issues.redhat.com/browse/RHOAIENG-1810)
- Adds the ability to mount self-signed certs to dsp v2.
- SSL_CERT_DIR takes care of the cert paths needed for different linux distros  that can be provided in the user image.
**Testing changes:**
Deploy a dspa using below yaml file. Create  pipeline runs by uploading the below provided pipelinespec yaml files using RHEL and Ubuntu images. Verify the pipelines run without errors and also if the volumeMounts in kfp-launcher pod contain the ca-bundle mount path. Also, we can verify the same in workflow YAML.
<details>
<summary>dspa.yaml </summary> 
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
name: sample …
```
=> Add ability to mount self-signed certs to dsp v2

backend/Dockerfile, backend/Dockerfile.driver, backend/Dockerfile.launcher, backend/Dockerfile.persistenceagent, backend/Dockerfile.scheduledworkflow, backend/src/apiserver/client/util.go, backend/src/apiserver/main.go
Resolves: 
* https://issues.redhat.com/browse/RHOAIENG-4383
Related: 
* https://issues.redhat.com/browse/RHOAIENG-4278
Use UBI images to deploy dspa similar to how we do it in downstream and remove passing default samples (we do not want to provide samples by default). 
To accomplish the latter, we have to provide a fix to not error out when no samples are provided. 
To test: 
* Set DSPA with enableSamplePipeline to false, and ensure no pipeline shows up. 
* Deploy the dspa with these new images built, run a pipeline
=> Use UBI images and make samples optional 

.github/resources/unittests/application_default_credentials.json, .github/workflows/unit-tests.yaml, backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml, backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
Resolve: https://issues.redhat.com/browse/RHOAIENG-4380
Run kfp unit tests on every pr with relevant code changes
None needed, just see the ci
=> Add unit test wf

backend/src/v2/component/launcher_v2.go, backend/src/v2/component/launcher_v2_test.go, backend/src/v2/config/env.go, backend/src/v2/objectstore/object_store.go, backend/src/v2/objectstore/object_store_test.go
Resolves: https://issues.redhat.com/browse/RHOAIENG-4450
This problem occurs when an executor tries to pull a cached image generated from another run. This error happens because, previously of the way the logic distinguished between "defaultBucket" and "nonDefaultBucket". The way to distinguish was based on path prefixes, for instance if  artifact is generated in run with id `runid1` it's stored in   `s3://bucket/runid1/artifact.txt`. If the run with id `runid2` wants to use "artifact.txt", it will expect it in  `s3://bucket/runid2/artifact.txt`, but looking at the metadata for artifact `artifact.txt` if will see that the prefix is different (i.e: `s3://bucket/runid1`), so it will ignore the default bucket, and regenerate the bucket config based on the new s3 path. 
In our carried patch …
=> fix: handle cached input in objstore

backend/src/apiserver/client_manager/client_manager.go
Resolves: https://issues.redhat.com/browse/RHOAIENG-3970
It is annoying when users see a "Initializing client manager" log and it's just stuck, not knowing whether db or minio connection failed, these simple logs will go a long way in helping troubleshoot such issues.
1. deploy dspa
2. check pipeline server logs, and see whether new logs show up in the changes
=> UPSTREAM: <carry>: chore: add meaningful logs to client initialization.

backend/src/v2/compiler/argocompiler/container.go, backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml, backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
follows up on dfe6edc, which does an EmptyDir mount for /.local and /.cache. /.config is another common write location, so EmptyDir mount that too.
To test, verify that this pipeline now works:
https://github.com/kubeflow/pipelines/blob/master/samples/v2/producer_consumer_param.py
**Checklist:**
=> UPSTREAM: <carry>: feat: mount EmptyDir volumes for launcher write locations pt 2

backend/src/v2/objectstore/object_store.go
Resolves [RHOAIENG-3774](https://issues.redhat.com/browse/RHOAIENG-3774) . This resolves the issue of having to specify the region within the host field in DSPA after already providing the same in "Region" field.
**Testing Instructions:**
1. Deploy DSPO
2. Create the secret 'aws-bucket-creds' in the namespace where you are going to deploy the DSPA. 
3. Deploy DSPA [a] attached below where the host is 's3.amazonaws.com'
4. Run the sample Pipeline and ensure it executes properly.
5. Deploy DSPA [b] attached below where the host is 's3.us-east-2.amazonaws.com'
6. Run the sample Pipeline and ensure it executes properly again.
<details>
<summary> DSPA [a] </summary>
```
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: …
```
=> UPSTREAM:<carry>:fix:Endpoint fix for AWS S3 Bucket Session

.github/workflows/build-prs.yml, tools/commit_checker/Dockerfile
=> chore: Add Commit Checker github action

.github/workflows/commit-check-pr.yml
=> Change Commit Checker to get the PR last commit

backend/Dockerfile, backend/Dockerfile.driver, backend/Dockerfile.launcher, backend/Dockerfile.persistenceagent, backend/Dockerfile.scheduledworkflow
Updated ubi8 image as suggested in [RHOAIENG-7423](https://issues.redhat.com//browse/RHOAIENG-7423)
**Testing instructions:**
Sanity Tests
**Checklist:**
=> UPSTREAM:<carry>:chore:RHOAIENG-7423 - Updated ubi8 image and go-toolset version

backend/src/v2/config/env.go, backend/src/v2/driver/driver.go
Resolves [RHOAIENG-7209](https://issues.redhat.com/browse/RHOAIENG-7209)
Fixed the issue with fetching the kfp-launcher default config when the provided pipelineroot is set via SDK or UI.
Testing instructions:
- Deploy dspa using the  dspa.pr-51.yaml in this PR.
-  While creating a pipeline run in the UI, provide the custom pipeline root in the parameters and the run should complete successfully.
-  Create another run without custom pipeline root and it should complete successfully.
**Checklist:**
=> UPSTREAM: <carry>: Fix for default Pipelineroot failures

api/go.mod
resolves: https://issues.redhat.com/browse/RHOAIENG-7308
Implemented fixes on my fork and tested out by importing the fork in my personal snyk account and making sure the CVEs were eliminated.
**Checklist:**
=> UPSTREAM: <carry>: Upgrade DSP api/go.mod package versions

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/storage/experiment_store.go
follup up to bf77909. Rename UpdateLastRun -> SetLastRunTimestamp
also tweak a related log message
/assign @HumairAK 
**Checklist:**
- [c] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).
=> UPSTREAM: <carry>: chore(backend): Rename UpdateLastRun -> SetLastRunTimestamp

.github/workflows/build-images.yaml
MLMD GRPC and Envoy image builds are no longer needed since we
leveragage service mesh and MR's images respectively.
=> UPSTREAM: <carry>: remove uneed image builds.

backend/src/agent/persistence/client/pipeline_client.go, backend/src/agent/persistence/main.go, backend/src/apiserver/main.go, backend/src/common/util/service.go, backend/src/v2/cacheutils/cache.go, backend/src/v2/cmd/driver/main.go, backend/src/v2/cmd/launcher-v2/main.go, backend/src/v2/compiler/argocompiler/argo.go, backend/src/v2/compiler/argocompiler/common.go, backend/src/v2/compiler/argocompiler/container.go, backend/src/v2/compiler/argocompiler/dag.go, backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml, backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml, backend/src/v2/compiler/argocompiler/testdata/importer.yaml, backend/src/v2/component/launcher_v2.go, backend/src/v2/driver/driver.go, backend/src/v2/driver/driver_test.go, frontend/server/configs.ts, frontend/server/utils.ts
Resolves: https://issues.redhat.com/browse/RHOAIENG-4968
Depends on: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/656
See DSPO pr for testing instructions
=> feat: add tls support for apiserver http/grpc
